### ISSUE TITLE
Install instructions to build each component instead of adding the TOS repository

### ISSUE THREAD

**Issue by CookieSource** [ODEX-TOS/tos-desktop-environment#120]
**Is your feature request related to a problem? Please describe.**
Currently the instructions state `if you are using an arch based distro that is not tos add the following repo to /etc/pacman.conf
[tos]
Server = https://repo.odex.be`
importing the key doesn't seem to work
**Describe the solution you'd like**
Instructions on how to build each component which is needed for TDE instead of adding a repository
**Describe alternatives you've considered**
Considered looking into building each package myself.
**Additional context**
none at the moment

**Comment by F0xedb** [comment]
Hi,

Sorry for the late response.
I've been busy lately.

You can find a list of all required package here:
https://github.com/ODEX-TOS/tos-desktop-environment/blob/release/build-utils/PKGBUILD#L30-L36

Most of those packages are already present in the base arch repositories.

The rest can be found here:
https://github.com/ODEX-TOS/tos-live/tree/master/repo/BUILD



I'll make a short example on how to build a specific package (You need to do this for every package)

One of the packages needed is `picom-tryone-tos` this is not present in the arch repository.
You can however find it here: https://github.com/ODEX-TOS/tos-live/tree/master/repo/BUILD
Specificaly this file: https://github.com/ODEX-TOS/tos-live/blob/master/repo/BUILD/PKGBUILD_PICOM
```bash
# make a directory to build all packages
mkdir -p BUILDS/PICOM
cd BUILDS/PICOM
curl https://raw.githubusercontent.com/ODEX-TOS/tos-live/master/repo/BUILD/PKGBUILD_PICOM > PKGBUILD

# The package should now be installed
makepkg -s -i
```


If you do this for every build then you should be able to compile this without all the extra packages.




Alternatively since you are running a base arch, you can add the repository and the required keys from here:
https://github.com/ODEX-TOS/tos-live/tree/master/repo/BUILD/KEYRING

You should see 3 files there:

- tos-revoked
- tos-trusted
- tos.gpg

These files can be put in `/usr/share/pacman/keyrings/`
Then rebuild your local keyring using the following command `sudo pacman-key --populate`

**Comment by CookieSource** [comment]
hey no worries keep up the good work ^_^ I'll see if I can build all files locally. 
I'm aware this is not even officially a final build yet so I'm pretty patient

**Comment by CookieSource** [comment]
So I'm slowly building everything from the pkgbuilds I have an issue with https://github.com/ODEX-TOS/tos-live/blob/master/repo/BUILD/PKGBUILD_CHECKUPDATE it doesn't output a correct checkupdates-aur-tos package it spits out an OS-CheckUpdates-AUR-0.04.tar.gz (which is incorrect) and an 
perl-checkupdates-aur-0.04-1-any.pkg.tar.zst

**Comment by CookieSource** [comment]
Everything seems to be working closing
